### PR TITLE
make it compatible with 2.401.1 jenkins

### PR DESCRIPTION
**Pull request by Absh-Day**
Tha parent pom for the plugin is still compatible with 2.3xx.x version so this change should be fine.

### Testing done

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by mawinter69** [comment]
This can't work. The plugin was already on 2.433 which is newer than what you want. It requires changes in core that were only released with that version.

**Comment by Absh-Day** [comment]
@mawinter69 Could you tell me features for which this plugin explicitly depends on 2.433 ?

**Comment by mawinter69** [comment]
It depends on 2.434 due to this change
https://github.com/jenkinsci/jenkins/pull/8705 at least, it might depend on other changes after 2.401 that I use because they were available

**Comment by Absh-Day** [comment]
> It depends on 2.434 due to this change [jenkinsci/jenkins#8705](https://github.com/jenkinsci/jenkins/pull/8705) at least, it might depend on other changes after 2.401 that I use because they were available

Great! Thanks for the info.

**Pull request closed without merging**
